### PR TITLE
Try latest aliases

### PR DESCRIPTION
**Pull request by jaraco**

### CODE REVIEW

**Comment by jaraco** [comment]
I was hoping this would trigger RTD, but it doesn't. I'll just push to main and force-push HEAD~1 if it doesn't work.

**Comment by jaraco** [comment]
[Didn't work](https://readthedocs.org/projects/jaracodevelop/builds/23363708/). Will have to wait some amount of time for [those changes](https://github.com/readthedocs/readthedocs.org/pull/11081) to be available.

**Comment by bswck** [comment]
Good to learn this is being worked on. I've wanted to use latest aliases recently.

**Comment by jaraco** [comment]
They rolled it out today and these updates are now in the skeleton.

**Comment by bswck** [comment]
> They rolled it out today and these updates are now in the skeleton.

Awesome news! I'll adopt it then too!

**Pull request closed without merging**
